name: $(Date:yyyyMMdd)$(Rev:.r)
parameters:
  - name: runIngegrationTests
    displayName: Run Integration Tests
    type: boolean
    default: true

trigger:
  branches:
    include:
    - develop
    - master
    - release/*

pr:
  branches:
    include:
    - develop
    - master
    - release/*

resources:
  repositories:
    - repository: templates
      type: github
      name: CluedIn-io/AzurePipelines.Templates
      endpoint: 'CluedIn-io'
      ref: refs/heads/refactor

pool:
  vmImage: 'windows-latest'

variables:
  - name: testFolderPath
    value: '$(Build.SourcesDirectory)/test'
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: true
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: true
  - name: buildConfiguration
    value: Release

steps:

   # Configure NuGet
  - task: NuGetAuthenticate@0
    displayName: 'Authenticate with nuget'
    
  - task: PowerShell@2
    displayName: 'Set Environment variables'
    inputs:
      targetType: inline
      script: |
        Write-Host ("##vso[task.setvariable variable=SERVICEBUS_ROOTMANAGESHAREDACCESSKEY_CONNECTIONSTRING;]$(ROOTMANAGESHAREDACCESSKEY_CONNECTIONSTRING)")
        Write-Host ("##vso[task.setvariable variable=SERVICEBUS_TESTQUEUE_CONNECTIONSTRING;]$(TESTQUEUE_CONNECTIONSTRING)")

  - template: crawler.build.yml@templates
    parameters:
      githubReleaseInMaster: true
      publicReleaseForMaster: true
      executeIngegrationTests: ${{ parameters.runIngegrationTests }}
      publishCodeCoverage: true