<Project>
  <PropertyGroup Label="Dependency Versions">
    <_EntityFramework>10.0.7</_EntityFramework>
    <_AutoFixture>5.0.0-preview0012</_AutoFixture>
    <_CluedIn>5.0.0-*</_CluedIn>
  </PropertyGroup>
  <ItemGroup>
    <!--
        Specified versions for dependencies in test projects

        MUST SPECIFY IN CSPROJ AS <PackageReference Name="<depName>" />
    -->
    <PackageReference Update="Microsoft.NET.Test.Sdk" Version="18.3.0" />
    <PackageReference Update="Azure.Messaging.ServiceBus" Version="7.2.1" />
    <PackageReference Update="AutoFixture.Xunit3" Version="$(_AutoFixture)" />
    <PackageReference Update="AutoFixture.Idioms" Version="$(_AutoFixture)" />
    <PackageReference Update="AutoFixture.AutoMoq" Version="$(_AutoFixture)" />
    <PackageReference Update="coverlet.msbuild" Version="2.8.0" />
    <PackageReference Update="xunit.v3" Version="3.2.2" />
    <PackageReference Update="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageReference Update="Moq" Version="4.13.1" />
    <PackageReference Update="Microsoft.EntityFrameworkCore" Version="$(_EntityFramework)" />
    <PackageReference Update="Microsoft.EntityFrameworkCore.InMemory" Version="$(_EntityFramework)" />
    <PackageReference Update="coverlet.collector" Version="1.2.0" />
    <PackageReference Update="FluentAssertions" Version="6.11.0" />
  </ItemGroup>
  <ItemGroup>
    <!--
        Specified versions for dependencies across the solution

        MUST SPECIFY IN CSPROJ AS <PackageReference Name="<depName>" />
    -->
    <PackageReference Update="CluedIn.Core" Version="$(_CluedIn)" />
    <PackageReference Update="CluedIn.Core.Agent" Version="$(_CluedIn)" />
    <PackageReference Update="CluedIn.Crawling" Version="$(_CluedIn)" />
    <PackageReference Update="CluedIn.DataStore" Version="$(_CluedIn)" />
    <PackageReference Update="Dapper" Version="2.0.138" />
    <PackageReference Update="Dapper.SqlBuilder" Version="2.0.35" />
    <PackageReference Update="Microsoft.AspNet.WebApi.Client" Version="5.2.7" />
  </ItemGroup>
  <ItemGroup Label="Global tools">
    <!--
            Automatically added to each project with :
            - IncludeAssets="Analyzers;Build"
            - PrivateAssets="All"

            DO NOT NEED TO BE ADDED AS A PACKAGEREFERENCE
        -->
    <!-- <GlobalPackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" /> -->
  </ItemGroup>
</Project>